apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-autoscaler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-autoscaler
  template:
    metadata:
      labels:
        app: ai-autoscaler
    spec:
      containers:
      - name: ai-autoscaler
        image: ai-autoscaler
        imagePullPolicy: Never
        ports:
        - containerPort: 80